version: '3'

services:
  fasttaskapi-dev:
    build:
      context: .
      target: build-stage
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - arangodb

  fasttaskapi-prod:
    build:
      context: .
      target: production-stage
    ports:
      - "8001:8000"
    environment:
      - ENVIRONMENT=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  arangodb:
    image: arangodb:latest
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - arangodata:/var/lib/arangodb3

volumes:
  arangodata:
